feat: Lists all GitHub Apps in an organization
UKHomeOffice/scm-repository-catalogue pull request #50
Opened 2022-12-12 09:48 UTC by mahrufiqbalHO

2022-12-13 09:03 UTC, arifulhaqueHO requested changes
Couple of things you should look at.

2022-12-16 12:40 UTC, arifulhaqueHO commented
Oh nice one Mahruf and Sam. Now if I can work on this a little bit, I can put React on my CV 😂.

2022-12-16 12:47 UTC, arifulhaqueHO approved these changes
Tested on local machine Looks good to me!

2022-12-16 12:55 UTC, samiwelthomasHO approved these changes

2022-12-16 13:08 UTC, merged